name: 'Generate README'
description: 'Generate a README.md file from a collection of markdown pages'
author: "Mike Schinkel <mike@newclarity.net>"
inputs:
  index_filepath:
    description: 'Filepath of the root index Markdown file containing [merge](./child.md) links'
    required: true
    default: './md/_index.md'
  readme_dir:
    description: 'The directory containing the README.md to update; typically this is simply dot (.)'
    required: true
    default: '.'
outputs:
  readme:
    description: 'Generated README.md content'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - /github/workspace/${{ inputs.index_filepath }}
  - /github/workspace/${{ inputs.readme_dir }}
