name: 'Generate README'
description: 'Generate a README.md file from a collection of markdown pages'
author: "Mike Schinkel <mike@newclarity.net>"
inputs:
  index_filepath:
    description: 'Filepath of the root index Markdown file containing [merge](./child.md) links'
    required: true
    default: './md/_index.md'
  readme_dir:
    description: 'The directory containing the README.md to update; typically this is simply dot (.)'
    required: true
    default: '.'

runs:
  using: "composite"
  steps:
  - name: Run Docker Container
    shell: bash
    run: |
      docker run --rm \
        -v $GITHUB_WORKSPACE:/app/repo \
        mikeschinkel/readme-merge:latest \
        /app/repo ${{ inputs.index_filepath }} ${{ inputs.readme_dir }}
